name: Alerts (notify on CI result)

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify PR on success
        if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests?.[0];
            if (pr) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `✅ CI passou no workflow **${context.payload.workflow_run.name}** (run #${context.payload.workflow_run.run_number}).`
              });
            }

      - name: Notify PR on failure
        if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion != 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests?.[0];
            if (pr) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `❌ CI falhou no workflow **${context.payload.workflow_run.name}** (run #${context.payload.workflow_run.run_number}). Veja os logs em Actions.`
              });
            }

      - name: Create repo issue on failed push
        if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion != 'success' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `❌ Alerta: CI falhou (run #${context.payload.workflow_run.run_number})`,
              body: `O workflow **${context.payload.workflow_run.name}** falhou no push para \`${context.payload.workflow_run.head_branch}\`.\n\nVeja os detalhes em Actions.`
            })