name: CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  package-and-deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build deliverable artifact (zip)
        run: |
          mkdir -p dist
          zip -r dist/projeto_notificacoes.zip src README.md requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pacote-entregavel
          path: dist/projeto_notificacoes.zip
          if-no-files-found: error
